/* tslint:disable */
// This file is generated
// Do not edit this file
import * as comment from "./comment/index";
export * as comment from "./comment/index";

export type Channels = {
  comment: comment.ChannelComment;
}
