/* tslint:disable */
// This file is generated
// Do not edit this file
import * as stripe from "./stripe/index";
export * as stripe from "./stripe/index";

export type Actions = {
  stripe: stripe.ActionStripe;
}
