/* tslint:disable */
// This file is generated
// Do not edit this file
import * as createTask from "./createTask/index";
export * as createTask from "./createTask/index";

export type Actions = {
  createTask: createTask.ActionCreateTask;
}
