/* tslint:disable */
// This file is generated
// Do not edit this file
import * as stripeButton from "./stripeButton/index";
export * as stripeButton from "./stripeButton/index";
import * as createTask from "./createTask/index";
export * as createTask from "./createTask/index";

export type Actions = {
  stripeButton: stripeButton.ActionStripeButton;
  createTask: createTask.ActionCreateTask;
}
