/* tslint:disable */
// This file is generated
// Do not edit this file
import * as taskCreated from "./taskCreated";
export * as taskCreated from "./taskCreated";
import * as hook from "./hook";
export * as hook from "./hook";

export type Events = {
  taskCreated: taskCreated.TaskCreated;
  hook: hook.Hook;
}
