/* tslint:disable */
// This file is generated
// Do not edit this file
import * as webhook from "./webhook";
export * as webhook from "./webhook";

export type Events = {
  webhook: webhook.Webhook;
}
