/* tslint:disable */
// This file is generated
// Do not edit this file
import * as taskCreated from "./taskCreated";
export * as taskCreated from "./taskCreated";

export type Events = {
  taskCreated: taskCreated.TaskCreated;
}
